# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tescoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(595, 355)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 60, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 55, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditnpm = QtWidgets.QLineEdit(Form)
        self.lineEditnpm.setGeometry(QtCore.QRect(150, 60, 113, 22))
        self.lineEditnpm.setObjectName("lineEditnpm")
        self.lineEditnama = QtWidgets.QLineEdit(Form)
        self.lineEditnama.setGeometry(QtCore.QRect(150, 100, 113, 22))
        self.lineEditnama.setObjectName("lineEditnama")
        self.lineEditkelas = QtWidgets.QLineEdit(Form)
        self.lineEditkelas.setGeometry(QtCore.QRect(150, 140, 113, 22))
        self.lineEditkelas.setObjectName("lineEditkelas")
        self.lineEditjurusan = QtWidgets.QLineEdit(Form)
        self.lineEditjurusan.setGeometry(QtCore.QRect(150, 180, 113, 22))
        self.lineEditjurusan.setObjectName("lineEditjurusan")
        self.lineEdittgllahir = QtWidgets.QLineEdit(Form)
        self.lineEdittgllahir.setGeometry(QtCore.QRect(150, 220, 113, 22))
        self.lineEdittgllahir.setObjectName("lineEdittgllahir")
        self.Button_insert = QtWidgets.QPushButton(Form)
        self.Button_insert.setGeometry(QtCore.QRect(150, 260, 111, 28))
        self.Button_insert.setObjectName("Button_insert")
        self.Button_loaddata = QtWidgets.QPushButton(Form)
        self.Button_loaddata.setGeometry(QtCore.QRect(290, 260, 261, 28))
        self.Button_loaddata.setObjectName("Button_loaddata")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(290, 60, 261, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.Button_caridata = QtWidgets.QPushButton(Form)
        self.Button_caridata.setGeometry(QtCore.QRect(30, 300, 81, 28))
        self.Button_caridata.setObjectName("Button_caridata")
        self.lineEditcaridata = QtWidgets.QLineEdit(Form)
        self.lineEditcaridata.setGeometry(QtCore.QRect(120, 300, 431, 21))
        self.lineEditcaridata.setObjectName("lineEditcaridata")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 55, 16))
        self.label_6.setObjectName("label_6")
        self.Button_insert.clicked.connect(self.insertmahasiswa)
        self.Button_loaddata.clicked.connect(self.loadmahasiswa)
        self.Button_caridata.clicked.connect(self.caridatamahasiswa)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def insertmahasiswa(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbkampus"
            )
            cursor = mydb.cursor()
            npm = self.lineEditnpm.text()
            nama = self.lineEditnama.text()
            kelas = self.lineEditkelas.text()
            jurusan = self.lineEditjurusan.text()
            tgl_lahir = self.lineEdittgllahir.text()

            sql = "INSERT INTO mahasiswa (npm,nama,kelas,jurusan,tgl_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npm,nama,kelas,jurusan,tgl_lahir)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Berhasil Disimpan")
            self.lineEditnpm.setText("")
            self.lineEditnama.setText("")
            self.lineEditkelas.setText("")
            self.lineEditjurusan.setText("")
            self.lineEdittgllahir.setText("")

        except mc.Error as e:
                self.label_6.setText("Data Gagal Disimpan")

    def loadmahasiswa(self):
        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="dbkampus")
            cursor = mydb.cursor()
            cursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

            self.label_6.setText("Data Mahasiswa Berhasil Ditampilkan")

        except mc.Error as e:
            self.label_6.setText(f"Error: {str(e)}")

    def caridatamahasiswa (self):
        keyword = self.lineEditcaridata.text().strip()
        if not keyword:
            self.label_6.setText("Masukkan kata kunci pencarian!")
            return

        try:
            mydb = mc.connect(host="localhost", user="root", password="", database="dbkampus")
            cursor = mydb.cursor()

            search_pattern = f"%{keyword}%"
            sql = """
                SELECT * FROM mahasiswa 
                WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s 
                OR jurusan LIKE %s OR tgl_lahir LIKE %s
            """
            cursor.execute(sql, (search_pattern, search_pattern, search_pattern, search_pattern, search_pattern))
            result = cursor.fetchall()

            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

            if not result:
                self.label_6.setText("Data tidak ditemukan!")
            else:
                self.label_6.setText(f"{len(result)} data ditemukan!")

        except mc.Error as e:
            self.label_6.setText(f"Error: {str(e)}")
        finally:
            if mydb.is_connected():
                cursor.close()
                mydb.close()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "npm"))
        self.label_2.setText(_translate("Form", "nama"))
        self.label_3.setText(_translate("Form", "kelas"))
        self.label_4.setText(_translate("Form", "jurusan"))
        self.label_5.setText(_translate("Form", "tgl_lahir"))
        self.Button_insert.setText(_translate("Form", "insert"))
        self.Button_loaddata.setText(_translate("Form", "load_data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "npm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "tgl_lahir"))
        self.Button_caridata.setText(_translate("Form", "cari_data"))
        self.label_6.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())